### ISSUE TITLE
Game crash ObjectDispenser:DropHeldItems

### ISSUE THREAD

**Issue by justin-lafayette** [yuval9313/ONI-Mods#1]
I have been encountering infrequent crashing due to a call from ObjectDispenser:DropHeldItems. The game points to Advanced Generatos as the cause. 

See link for log: [output_log_5-13_2-43](https://github.com/justin-barfield/ONI-Mods/blob/master/output_log_5-13_2-43.txt)

This error has also appeared with Tiny Battery but I dont think you are the editor for the mod. I am happy to provide more details to assist in fixing this bug. Just let me know what may be needed.

**Comment by yuval9313** [comment]
I couldn't replicate this issue, please provide the next details:
mod version,
game version,

Try this:
disable all the mods, start the game and repost the log

Good job, reporting this bug and thank you

**Comment by justin-lafayette** [comment]
I went through about 40+ cycles today without error but did not test with all other mods disabled. 

Mod: https://github.com/justin-barfield/ONI-Mods/blob/master/AdvancedGenerators.dll
https://github.com/justin-barfield/ONI-Mods/blob/master/AdvancedGenerators.pdb

Last mod update: April 4, 2020 23:01

Game version: AP-410209

Save: https://github.com/justin-barfield/ONI-Mods/blob/master/Mirrage%20Cycle%20904.sav

Output log: https://github.com/justin-barfield/ONI-Mods/blob/master/output_log_advancedGeneratos_5-14_3-21.zip

**Comment by yuval9313** [comment]
So, after exploring your log for a bit, I've notices that this is actually not my assembly that causes the issue,
However, I would like you to try something out for me before I close it to absolutely fix your issue, rather then closing this issue


Start a new save (sandbox), the same mods selected, except Advanced Generators, if error occurs, screenshot it and post it and the log, again
Then for house keeping, start a new save, this time only the Advanced Generators mod and test if the issue re-happens
