### ISSUE TITLE
Sweet Dreams Update

### ISSUE THREAD

**Issue by mayday6971** [yuval9313/ONI-Mods#8]
After the latest "Sweet Dreams" module update. This mod no longer is working. Are there any plans to update the mod?

Thanks!

**Comment by mayday6971** [comment]
Just in case it helps.

https://forums.kleientertainment.com/game-updates/oni-alpha/

**Modding:**
* Refactored TagBits usage, removing Prefab ID from tags.
* TagBits has been reduced to 256 bits.
* The prefab’s ID (KPrefabID.PrefabTag) will no longer be contained in KPrefabID.tags (and KPrefabID.Tags by extension).
* KPrefabID.HasTag (and etc) will now also check the prefab’s ID to maintain compatibility with existing code.
* TagBits will continue to exist for now, but using it for comparison will no longer match against the prefab ID. 
* Any code that previously used TagBits to compare many different prefab IDs (Fetch chores, filtered storage) against prefabs now uses a HashSet of IDs, which will only match against the prefab ID (for performance reasons). For fetch chores, the required tag and forbidden tag facilities can still be used to match against a prefab’s non-ID tags. 
* Increased maximum number of supported elements. The type for storing element indices has changed from byte to ushort. 
* Removed previously deprecated "featureTemplates" setting from worldgen. It was primarily used in world traits. Use "additionalWorldTemplateRules" instead.
* FMOD major version upgrade to 2.02.07. EventRef was removed and replaced with new class EventReference.

**Comment by yuval9313** [comment]
Working on it
Thank you!

**Comment by yuval9313** [comment]
Btw, How did you find the modding information?

**Comment by mayday6971** [comment]
> Btw, How did you find the modding information?

https://forums.kleientertainment.com/game-updates/oni-alpha/

In the release notes, there is an area you can click on that says "review hidden contents". Klei thinks of it as spoilers, but it is often the most useful information on the entire page. It often has very good information for modders.

BTW, thanks for making this module, and thanks for fixing them!

Cheers!
